"""Quiz service orchestrating generation, validation, scoring, and rewards."""

from datetime import date
from typing import Any

from sqlalchemy.ext.asyncio import AsyncSession

from app.database.models.quiz import Quiz
from app.database.repositories.quiz import QuizRepository
from app.database.repositories.user import UserRepository
from app.services.achievements.service import AchievementService
from app.services.ai.client import AIService, ai_service
from app.services.progress.gamification import calculate_quiz_xp


class QuizService:
    def __init__(
        self,
        session: AsyncSession,
        ai: AIService | None = None,
    ) -> None:
        self.session = session
        self.quiz_repo = QuizRepository(session)
        self.user_repo = UserRepository(session)
        self.ai = ai or ai_service
        self.achievement_service = AchievementService(session)

    async def generate_and_save_quiz(
        self,
        user_id: int,
        subject_id: int | None,
        subject_name: str,
        difficulty: str = "medium",
        count: int = 5,
        language: str = "en",
    ) -> Quiz:
        """Generate questions via AI and save to database."""
        recent_questions = await self.quiz_repo.get_recent_user_questions(
            user_id=user_id,
            subject_id=subject_id,
            limit=25,
        )

        raw_questions = await self.ai.generate_quiz(
            subject=subject_name,
            difficulty=difficulty,
            count=count,
            language=language,
            exclude_questions=recent_questions,
        )

        # Validate and clean questions
        validated: list[dict[str, Any]] = []
        for q in raw_questions:
            if "question" in q and "options" in q and "correct_option" in q:
                options = q["options"]
                if isinstance(options, dict) and len(options) >= 2:
                    validated.append({
                        "question": q["question"],
                        "options": options,
                        "correct_option": str(q["correct_option"]).strip().upper(),
                        "explanation": q.get("explanation", ""),
                    })

        if not validated:
            raise ValueError("No valid questions generated by AI.")

        quiz = await self.quiz_repo.create_quiz_with_questions(
            user_id=user_id,
            subject_id=subject_id,
            title=f"{subject_name} Quiz",
            difficulty=difficulty,
            questions_data=validated,
        )
        return quiz

    async def submit_answer(
        self,
        quiz_id: int,
        question_id: int,
        user_id: int,
        selected_option: str,
        correct_option: str,
    ) -> bool:
        """Record user answer and return True if correct."""
        is_correct = selected_option.strip().upper() == correct_option.strip().upper()
        await self.quiz_repo.record_answer(
            quiz_id=quiz_id,
            question_id=question_id,
            user_id=user_id,
            selected_option=selected_option,
            is_correct=is_correct,
        )
        return is_correct

    async def finalize_quiz(
        self,
        quiz_id: int,
        user_id: int,
        score: int,
        total_questions: int,
    ) -> tuple[int, list[Any]]:
        """Finalize quiz, award XP, update streak, check achievements.

        Returns (xp_earned, unlocked_achievements).
        """
        xp_earned = calculate_quiz_xp(score, total_questions)
        await self.quiz_repo.finish_quiz(quiz_id, score, xp_earned)

        # Award XP
        await self.user_repo.add_xp(user_id, xp_earned)

        # Update streak
        await self.user_repo.update_streak(user_id, date.today())

        # Check achievements
        user = await self.user_repo.get_by_id(user_id)
        unlocked = []
        if user:
            unlocked = await self.achievement_service.check_and_unlock(user)

        return xp_earned, unlocked
